/* Fallback menu data — used when the API is unreachable (e.g. static hosting). */
window.BAHAMAS_MENU_FALLBACK = [
  {
    "id": "grill-fried-pork",
    "name": "Fried Pork",
    "category": "grill",
    "price": 20000,
    "description": "Well-seasoned deep-fried pork portions, crispy and hot.",
    "image": "https://images.pexels.com/photos/1352296/pexels-photo-1352296.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Popular",
    "combo": false,
    "from": false
  },
  {
    "id": "grill-pork-kikalayi",
    "name": "Pork Kikalayi",
    "category": "grill",
    "price": 25000,
    "description": "Sautéed pork with vegetables, spices & matooke or Irish.",
    "image": "https://images.pexels.com/photos/2233729/pexels-photo-2233729.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Local",
    "combo": false,
    "from": false
  },
  {
    "id": "grill-pork-skewers",
    "name": "Pork Skewers",
    "category": "grill",
    "price": 15000,
    "description": "Tender flame-grilled pork skewers (2–3 sticks).",
    "image": "https://images.pexels.com/photos/8477/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "grill-pork-chops",
    "name": "Pork Chops",
    "category": "grill",
    "price": 22000,
    "description": "Juicy grilled pork chops marinated in aromatic herbs.",
    "image": "https://images.pexels.com/photos/8308126/pexels-photo-8308126.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "grill-pork-ribs",
    "name": "Pork Ribs",
    "category": "grill",
    "price": 25000,
    "description": "Slow-grilled ribs glazed with smoky BBQ.",
    "image": "https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Chef's Pick",
    "combo": false,
    "from": false
  },
  {
    "id": "grill-family-platter",
    "name": "Family Grill Platter",
    "category": "grill",
    "price": 85000,
    "description": "Assorted pork, chicken, skewers & sides. Serves 3–4.",
    "image": "https://images.pexels.com/photos/1247755/pexels-photo-1247755.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "grill-bahamas-combo",
    "name": "Bahamas Pork Combo",
    "category": "grill",
    "price": 25000,
    "description": "Fried pork + side + small kachumbari.",
    "image": "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "grill-kikalayi-combo",
    "name": "Pork Kikalayi Combo",
    "category": "grill",
    "price": 28000,
    "description": "Pork kikalayi with an extra side.",
    "image": "https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "chicken-quarter",
    "name": "Quarter Chicken",
    "category": "chicken",
    "price": 18000,
    "description": "Flame-grilled quarter chicken, signature seasoning.",
    "image": "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=600&q=80",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "chicken-half",
    "name": "Half Chicken",
    "category": "chicken",
    "price": 22000,
    "description": "Juicy half chicken grilled over open flame.",
    "image": "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "chicken-whole",
    "name": "Whole Chicken",
    "category": "chicken",
    "price": 40000,
    "description": "Full flame-grilled chicken, ideal for sharing.",
    "image": "https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "chicken-kikalayi",
    "name": "Chicken Kikalayi",
    "category": "chicken",
    "price": 28000,
    "description": "Fried chicken tossed with cabbage, carrots & garlic.",
    "image": "https://images.pexels.com/photos/2955819/pexels-photo-2955819.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Local",
    "combo": false,
    "from": false
  },
  {
    "id": "chicken-half-combo",
    "name": "Half Chicken Combo",
    "category": "chicken",
    "price": 28000,
    "description": "Half grilled chicken + choice of 2 sides.",
    "image": "https://images.pexels.com/photos/2271107/pexels-photo-2271107.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "chicken-feast",
    "name": "Whole Chicken Feast",
    "category": "chicken",
    "price": 55000,
    "description": "Whole chicken + large chips + salad. Serves 3–4.",
    "image": "https://images.pexels.com/photos/6210747/pexels-photo-6210747.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "chicken-rolex-combo",
    "name": "Chicken Rolex Combo",
    "category": "chicken",
    "price": 15000,
    "description": "Chicken rolex + a side portion of chips.",
    "image": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
    "badge": "Combo",
    "combo": true,
    "from": false
  },
  {
    "id": "quick-pork-soup",
    "name": "Pork Soup",
    "category": "quick",
    "price": 12000,
    "description": "Rich traditional pork broth with local spices.",
    "image": "https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "quick-chicken-soup",
    "name": "Chicken Soup",
    "category": "quick",
    "price": 12000,
    "description": "Hearty chicken broth, made fresh daily.",
    "image": "https://images.pexels.com/photos/6249508/pexels-photo-6249508.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "quick-chicken-rolex",
    "name": "Chicken Rolex",
    "category": "quick",
    "price": 10000,
    "description": "Rolled chapati with egg, veg & grilled chicken.",
    "image": "https://images.pexels.com/photos/5175537/pexels-photo-5175537.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "quick-pork-rolex",
    "name": "Pork Rolex",
    "category": "quick",
    "price": 10000,
    "description": "Rolled chapati with egg, veg & seasoned pork.",
    "image": "https://images.pexels.com/photos/4676640/pexels-photo-4676640.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "quick-chips",
    "name": "Chips / Fries",
    "category": "quick",
    "price": 8000,
    "description": "Golden crispy fries, freshly prepared.",
    "image": "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "quick-kachumbali",
    "name": "Fresh Kachumbali",
    "category": "quick",
    "price": 5000,
    "description": "Crisp tomatoes, onions, herbs & local dressing.",
    "image": "https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-espresso",
    "name": "Espresso / Coffee",
    "category": "drinks",
    "price": 5000,
    "description": "Freshly brewed, bold and aromatic.",
    "image": "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Coffee",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-cappuccino",
    "name": "Cappuccino / Latte",
    "category": "drinks",
    "price": 8000,
    "description": "Velvety milk coffee with rich espresso.",
    "image": "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Coffee",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-smoothie",
    "name": "Fruit Smoothie",
    "category": "drinks",
    "price": 10000,
    "description": "Mango, passion, banana, strawberry or mixed.",
    "image": "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Fresh",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-juice",
    "name": "Natural Fresh Juice",
    "category": "drinks",
    "price": 7000,
    "description": "Mango, passion, pineapple or watermelon.",
    "image": "https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Fresh",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-beer",
    "name": "Local Beer",
    "category": "drinks",
    "price": 6000,
    "description": "Nile Special, Club, Bell, Guinness & more.",
    "image": "https://images.pexels.com/photos/1552750/pexels-photo-1552750.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Beer",
    "combo": false,
    "from": true
  },
  {
    "id": "drink-whisky",
    "name": "Whisky Shot",
    "category": "drinks",
    "price": 10000,
    "description": "Premium whisky & spirits (ask for brands).",
    "image": "https://images.pexels.com/photos/602750/pexels-photo-602750.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Whisky",
    "combo": false,
    "from": true
  },
  {
    "id": "drink-cocktail",
    "name": "Classic Cocktail",
    "category": "drinks",
    "price": 15000,
    "description": "Refreshing cocktails from our bar team.",
    "image": "https://images.pexels.com/photos/1170599/pexels-photo-1170599.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Cocktail",
    "combo": false,
    "from": false
  },
  {
    "id": "drink-soda",
    "name": "Soda / Water",
    "category": "drinks",
    "price": 3000,
    "description": "Soft drinks, mineral water & chilled refreshers.",
    "image": "https://images.pexels.com/photos/2775860/pexels-photo-2775860.jpeg?auto=compress&cs=tinysrgb&w=600",
    "badge": "Cold",
    "combo": false,
    "from": true
  }
];
